require "active_support/core_ext/hash/indifferent_access"
require "active_support/core_ext/hash/keys"
require "active_support/core_ext/hash/slice"
require "active_support/core_ext/object/try"
require "active_support/core_ext/string/inflections"
require "faraday"
require "json"
require "json_schema"

require "jsonism/client"
require "jsonism/definer"
require "jsonism/link"
require "jsonism/request"
require "jsonism/version"
